
package com.ho.cm.ui;

import com.ho.cm.bao.BaoFactory;
import com.ho.cm.bao.BillBao;
import com.ho.cm.bao.StockItemBao;
import com.ho.cm.dto.BillDto;
import com.ho.cm.dto.BillRowDto;
import com.ho.cm.dto.StockItemDto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author h.omar
 */
public class InsertNewBill extends javax.swing.JPanel {


    BillBao BillBaoObject = new BaoFactory().createBillBao();
    StockItemBao StockItemBaoObj = new BaoFactory().createStockItemBao();
    List<StockItemDto> allItems = StockItemBaoObj.allItem();

    /** Creates new form InsertNewBill */
    public InsertNewBill() {
        initComponents();
        listcombo(allItems);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customeName = new javax.swing.JTextField();
        customerPhone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phoneErrorLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billContTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        itemsNameCombo = new javax.swing.JComboBox();
        moveRowBtn = new javax.swing.JButton();
        pricesCombo = new javax.swing.JComboBox();
        countCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Customer Name");

        customeName.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N

        customerPhone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customerPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerPhoneKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Phone ");

        phoneErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(customeName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customeName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bill content", 0, 0, new java.awt.Font("Adobe Arabic", 1, 36))); // NOI18N

        billContTable.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        billContTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Number of Item", "Price per Item"
            }
        ));
        billContTable.setRowHeight(30);
        billContTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billContTableMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(billContTable);
        billContTable.getColumnModel().getColumn(0).setHeaderValue("Item Name");
        billContTable.getColumnModel().getColumn(1).setHeaderValue("Number of Item");
        billContTable.getColumnModel().getColumn(2).setHeaderValue("Price per Item");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        totalLabel.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        totalLabel.setText("Total  :-");

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        itemsNameCombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        itemsNameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Items" }));
        itemsNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsNameComboActionPerformed(evt);
            }
        });

        moveRowBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        moveRowBtn.setText("+");
        moveRowBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveRowBtnMouseClicked(evt);
            }
        });

        pricesCombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pricesCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Prices" }));

        countCombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        countCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Current Available" }));

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel3.setText("Items Name ");

        jLabel4.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel4.setText("Price");

        jLabel5.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel5.setText("Current No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moveRowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemsNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pricesCombo, 0, 169, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(countCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(moveRowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pricesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemsNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
    }//GEN-END:initComponents

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
                                            
        BillDto bill = new BillDto();

        //  read the bill content and pass it
        bill.setBillDate(new Date(System.currentTimeMillis())); // passing current time
        bill.setCustomerPhone(customerPhone.getText()); // passing customer phone
        bill.setCustomerName(customeName.getText()); // passing customer full name
        // call method to save the billContTableRead returned value in the table

        bill.setBillRows(billContTableRead()); // passing  table data

        if (BillBaoObject.saveBill(bill))
            JOptionPane.showMessageDialog(this, "Successfully Saving");
        else
            JOptionPane.showMessageDialog(this, "there are an error");
    }//GEN-LAST:event_saveBtnMouseClicked

    private void customerPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerPhoneKeyTyped
      
        if (customerPhone.getText().toLowerCase().contentEquals("qwertyuioplkjhgfdsazxcvbnm-+/.';[]}{>?<:|~!@#%^*()")) {
            phoneErrorLabel.setText("this cant be a number Ex-->01123");
        } else
            phoneErrorLabel.setText("");
      
    }//GEN-LAST:event_customerPhoneKeyTyped

    private void itemsComboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsComboMouseExited
        
        //billContTable.setValueAt(itemsCombo.getSelectedObjects(), billContTable.getRowCount(), 0);    
        
        
        
    }//GEN-LAST:event_itemsComboMouseExited

    private void billContTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billContTableMouseExited
        List<BillRowDto> bills = billContTableRead();
        float total = 0f;
        if (bills != null) {
            try {
                for (int i = 0; i < bills.size(); i++) // loop on the bill's items
                {
                    float totalPerRow =
                        bills.get(i).getNumberofItemes() *
                        bills.get(i).getPricePerItem(); // this is {price per item *number of items}
                    total += totalPerRow;
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        totalLabel.setText("Total :  " + total + " LE");
 
    }//GEN-LAST:event_billContTableMouseExited

    private void moveRowBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveRowBtnMouseClicked
        synCombo();
        moveItemes();
       
    }//GEN-LAST:event_moveRowBtnMouseClicked

    private void itemsNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsNameComboActionPerformed
        synCombo();
      
    }//GEN-LAST:event_itemsNameComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable billContTable;
    private javax.swing.JComboBox countCombo;
    private javax.swing.JTextField customeName;
    private javax.swing.JTextField customerPhone;
    private javax.swing.JComboBox itemsNameCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton moveRowBtn;
    private javax.swing.JLabel phoneErrorLabel;
    private javax.swing.JComboBox pricesCombo;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables


    // this method read the rows
    public List<BillRowDto> billContTableRead() {
        List<BillRowDto> billRows = new ArrayList<>();
        try {
            // loop on rows and collect data
            for (int i = 0; i < billContTable.getRowCount(); i++) {
                BillRowDto billRow = new BillRowDto();
                billRow.setItemName(billContTable.getValueAt(i, 0).toString()); // get col 1 as string
                billRow.setNumberofItemes(Integer.parseInt(billContTable.getValueAt(i,
                                                                                    1).toString())); // pass col 2 as integer value
                billRow.setPricePerItem(Float.parseFloat(billContTable.getValueAt(i,
                                                                                  2).toString())); // pass col 3 as float

                billRows.add(billRow);

            }
        } catch (Exception e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog(this , "Your Input not proper Please Edite it and fill  all fields ");

        }
        return billRows;
    }

    // this method to make a list in our combo box
    void listcombo(List<StockItemDto> list) {
        for (int i = 0; i < list.size(); i++) {
            // check that available number is > 0
            if (list.get(i).getId() > 0) {
                itemsNameCombo.addItem(list.get(i).getName());
                pricesCombo.addItem(list.get(i).getPrice());
                countCombo.addItem(list.get(i).getCurrentNumber());

            }
        }

    }

    void moveItemes() {
        // this method add a new row to the table
        if (itemsNameCombo.getSelectedIndex() > 0)

        {
            DefaultTableModel model = (DefaultTableModel) billContTable.getModel();
            model.addRow(new Object[] { itemsNameCombo.getSelectedItem(), "1", pricesCombo.getSelectedItem() });
        } else
            JOptionPane.showMessageDialog(this, "please choose an item to add ");
    }

    void synCombo() {
        pricesCombo.setSelectedIndex(itemsNameCombo.getSelectedIndex());
        countCombo.setSelectedIndex(itemsNameCombo.getSelectedIndex());

    }
}


